resources:
  - name: repo_kubedirector
    type: GitRepo
    configuration:
      gitProvider: anujgithub
      path: anujrajkumar/kubedirector
      branches:
         include: ^{{gitBranch}}$
      buildOn:
        commit: true
        pullRequestCreate: true
        
pipelines:
  - name: kubedirector_poc
    configuration:
      nodePool: AJNodes
      environmentVariables:
        readOnly:
          harborRegistry: "bd-harbor-registry.mip.storage.hpecorp.net"
          harborProject: "docker-local"
          jfrogRegistry: "bd-jfrog-artifactory.mip.storage.hpecorp.net:80"
          jfrogProject: "docker-local"
      integrations:
        - name: notifySMTP
        - name: jfrog
        - name: ezmeral_slack
        - name: xray
    steps:
      - name: Scan
        type: Bash
        configuration:
          inputResources:
            - name: repo_kubedirector
              trigger: true
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-c7go
                tag: "1.17"
                options: "-v /usr/bin/jf:/usr/bin/jf"
        execution:
          onExecute:
            - pushd $res_repo_kubedirector_resourcePath
            - /usr/bin/jf config add --url=http://bd-jfrog-artifactory.mip.storage.hpecorp.net --interactive=false --access-token $int_xray_token
            - /usr/bin/jf audit --watches 'test_watch' > static_code_analysis_report
            - cat static_code_analysis_report
            - cat build/Dockerfile
            - add_run_files static_code_analysis_report sast_report
            
      - name: Build
        type: Bash
        configuration:
          inputResources:
            - name: repo_kubedirector
              trigger: false
          inputSteps: 
            - name: Scan
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-c7go
                tag: "1.17"
                options: "-v /usr/bin/jf:/usr/bin/jf"
        execution:
          onExecute:
           - if [[ ${step_triggered_by_resource_name} == "repo_kubedirector" ]]; then changed_files=compare_git --path $res_repo_kubedirector_resourcePath --commit-range HEAD~1..HEAD; fi
           - echo "Changed files  -$changed_files"
           - cd $res_repo_kubedirector_resourcePath/
           - RELEASE_VERSION=v0.15.2
           - curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
           - chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
           - go get -u golang.org/x/lint/golint
           - go mod tidy
           - make build
